# Generated by Django 6.0.6 on 2026-06-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('archivo_pdf', models.FileField(upload_to='libros_pdfs/')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('grado_objetivo', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('general', 'General (Todos)')], default='general', max_length=20)),
                ('ejemplares_disponibles', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
